services:
  - type: web
    name: promptcraft-guild-api
    env: docker
    rootDir: promptcraft-guild-api
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PROMETHEUS_MODEL
        value: prometheus-2
      - key: MISTRAL_MODEL
        value: mistral-7b-instruct
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false 